import Head from "next/head";
import { Inter } from "next/font/google";
import IndexPage from '@/components/IndexPage/IndexPage'
import MissionsProvider from "@/contexts/missions-context";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet" />

      </Head>
      <MissionsProvider>
        <IndexPage/ >
      </MissionsProvider>
    </>
  );
}
